#PBS -l nodes=1:ppn=1
#PBS -q batch
#PBS -j oe
 
cd $PBS_O_WORKDIR


# resize from center, 200 bp

module load R

Rscript resize_peak.R ./


wait

#### Delete tracks with negative number for start site after resizing
for f in *.resized.bed
do
        srt=`cat $f | awk '$2 < 0' | wc -l`
        if [ ${srt} -gt 0 ]
        then
                echo "ACTION: del" ${srt} "line(s) from" $f
                cat $f | sed '/-[0-9]/d' > tmp
                mv tmp ${f}
        fi
done

#rm *.slop.bed
